import Head from "next/head";
import styles from "../styles/Home.module.css";
import ArtCard from "../components/ArtCard";
import testData from "../testdata/imgdata.json";
import testCats from "../testdata/category.json";
import { Container } from "react-bootstrap";
import CategorySelector from "../components/CategorySelector";
import { useState, useEffect } from "react";

export default function Home() {
  const images = testData.images.filter((image) => image.display);
  images.forEach((image) => (image._display = true));

  const artCards = [];

  testData.images.filter((image) => {
    if (image.display) artCards.push(<ArtCard key={image.id} {...image} />);
  });
  const [cards, setCards] = useState(artCards);
  const [show, setShow] = useState([]);

  const handleFilter = (categories) => {
    for (let i = 0; i < categories.length; i++) {
      for (let j = 0; j < artCards.length; j++) {
        if (categories[i] && artCards[j].props.categoryIds.includes(i+1)) {
          artCards[j].props.show = true;
          break;
        }
        artCards[j].props.show = false;
      }
    }
    setCards(artCards);
  };
  const selectorData = {
    cats: testCats.categories,
    cards: cards,
    onChange: handleFilter,
  };

  const gg = (artCard) => {
    console.log(artCard);
    return artCard;
  };

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          style={{ backgroundColor: "lightblue", margin: "20", padding: 10 }}
          className="sticky-top"
        >
          <CategorySelector {...selectorData} />
          <div></div>
        </div>
        <div className={styles.grid}>{artCards}</div>
      </main>
    </Container>
  );
}
